spring.application.name=Qpay
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ZeroQDB
spring.datasource.username=postgres
spring.datasource.password=Goenka2193

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
# JWT
jwt.secret=QPay_ZeroQ_Secret_Key_For_HMAC_SHA256_Algorithm_2026_Secure!!
jwt.expiration-ms=86400000

# SMS Provider
sms.provider=twilio

# Twilio
twilio.account-sid=ACceeacbabe9580ef18c25dd8e175b7f17
twilio.auth-token=e2c3ea0825dfc7c5c26cfceed14e6d48
twilio.phone-number=+14156920402
twilio.from-number= +14156920402
twilio.sms-enabled=true

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000

#MogoDb
spring.data.mongodb.uri=mongodb://localhost:27017/zeroQDB
spring.data.mongodb.database=zeroQDB

# OTP Config
otp.expiry-minutes=5
otp.max-per-hour=10
otp.resend-cooldown-seconds=30
# Development ke liye
otp.max-resend-per-hour=20

